apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
spec:    
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
      