apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
stringData:
  sa-password: #{stringData:sa-password}
  connectionstring: #{stringData:connectionstring}
  SA_PASSWORD: #{stringData:SA_PASSWORD}