apiVersion: v1
kind: Service
metadata:
  name: shoppingcart-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: shoppingcart
  ports:
    - port: 5012
      targetPort: 5012
      name: http-port
    - port: 5013
      targetPort: 5013
      name: https-port