apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingcartservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: shoppingcart
  template:
    metadata:
      labels:
        component: shoppingcart   
    spec:
      containers:
        - name: shoppingcart
          image: octopussamples/octopetshop-shoppingcartservice          
          env:
            - name: OPSConnectionString
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: connectionstring