apiVersion: v1
kind: Service
metadata:
  name: mssql
spec:
  type: ClusterIP
  selector:
    app: mssql 
    app.kubernetes.io/name: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433